### PR TITLE
Avoiding rounding issues in JSON filter settings

### LINKED ISSUE #155: Different rounding of identity in links and filters
This error is a little subtle and I stumbled across it by chance. When you run alitv.pl on the two sequences in [this gist](https://gist.github.com/iimog/5267a9046925a7e2834b96a2c61d8674) like this:
```
alitv.pl --project out seq0.fa seq1.fa
```
you end up with the json file also in the gist. When you visualize this file in the AliTV web interface you do not see any alignment despite the two sequences being almost identical.

Upon closer inspection I found the error: The `filters.links.maxLinkIdentity` is dynamically set to the link with highest identity found (with lots of precision), in this case: `99.8955395382848`.
However the identity for the link is rounded to one decimal position so is `99.9`.
As this is higher than the `maxLinkIdentity` the link is not shown. This is clearly a bug.

I can imagine multiple ways to address this issue:
1. do not set `maxLinkIdentity` dynamically, rather always set it to 100
2. round `maxLinkIdentity` and the separate links to the same number of decimal points

As a workaround if this case happens it helps to re-adjust the identity slider (set it a little lower, apply, set it to 100% and apply again). In this case with 99.89 it looks like it is fixed at 100 already...

### PR DESCRIPTION
**Pull request by greatfireball**
This version avoids the issues described in #155 and ensures, that the default filter settings inside the produced JSON are integers and include the actual values.

This is ensured by truncating the min value and rounding to the next integer (or 100) for the max value.

Moreover, the version is the base for thev1.0.6 release.

Fix #155

### CODE REVIEW

File: lib/AliTV.pm [hunk 1]
```diff
@@ -268,9 +268,9 @@ sub get_json
                                     },
                          'links' => {
                                       'invisibleLinks' => {},
-                                      'maxLinkIdentity' => $self->{_links_max_id}+0,
+                                      'maxLinkIdentity' => ($self->{_links_max_id} >= 100) ? 100: int($self->{_links_max_id}+1),
```
Comment (iimog) [inline lib/AliTV.pm]: This works as intended but is not easy to understand at first glance. Especially the int($self...+1) part. It might be more readable to use `ceil` from the `POSIX` package. Not sure if this is a core module or if it introduces another dependency. In this case I'll vote for keeping your implementation

File: lib/AliTV.pm [hunk 2]
```diff
@@ -268,9 +268,9 @@ sub get_json
...
                                       'maxLinkLength' => $self->{_links_max_len}+0,
-                                      'minLinkIdentity' => $self->{_links_min_id}+0,
+                                      'minLinkIdentity' => int($self->{_links_min_id}+0),
```
Comment (iimog) [inline lib/AliTV.pm]: Maybe `floor` from `POSIX` makes it absolutely clear that it is rounded to the next lower int.

**Review by iimog — APPROVED** [review]
Some ideas for potential improvements of readability, nothing blocking.

**Comment by greatfireball** [comment]
`floor/trunc` and `ceil` would be possible, due to POSIX is a core module. If you would prefer it, I will implement it.

Other possibility would be better commenting to ensure, everybody understands those code lines. Whatever you want... Just let me know.

**Comment by iimog** [comment]
I favor readable, self-explanatory code over code comments. So using the POSIX functions would be my preferred solution. Thanks
